ALTER TABLE users ALTER COLUMN id TYPE BIGINT;
ALTER TABLE clients ALTER COLUMN id TYPE BIGINT;
ALTER TABLE health_plans ALTER COLUMN id TYPE BIGINT;
ALTER TABLE quotations ALTER COLUMN id TYPE BIGINT;
ALTER TABLE refresh_token ALTER COLUMN id TYPE BIGINT;

ALTER TABLE clients ALTER COLUMN broker_id TYPE BIGINT;
ALTER TABLE quotations ALTER COLUMN client_id TYPE BIGINT;
ALTER TABLE quotations ALTER COLUMN health_plan_id TYPE BIGINT;
ALTER TABLE refresh_token ALTER COLUMN user_id TYPE BIGINT;